import 'jquery';while(globalThis.elgg===undefined){await new Promise(r=>setTimeout(r,10))}
var elgg=globalThis.elgg||{};elgg.assertTypeOf=function(type,val){if(typeof val!==type){throw new TypeError("Expecting param of "+arguments.caller+"to be a(n) "+type+". Was actually a(n) "+typeof val+".")}};elgg.normalize_url=function(url){url=url||'';elgg.assertTypeOf('string',url);function validate(url){url=elgg.parse_url(url);if(url.scheme){url.scheme=url.scheme.toLowerCase()}
if(url.scheme=='http'||url.scheme=='https'){if(!url.host){return!1}
if(!(new RegExp("^([a-zA-Z0-9][a-zA-Z0-9\\-\\.]*)$","i")).test(url.host)||url.host.charAt(-1)=='.'){return!1}}
if(!url.scheme||!url.host&&url.scheme!='mailto'&&url.scheme!='news'&&url.scheme!='file'){return!1}
return!0};if(url.indexOf('http:')===0||url.indexOf('https:')===0||url.indexOf('javascript:')===0||url.indexOf('mailto:')===0){return url}else if(validate(url)){return url}else if((new RegExp("^(\\#|\\?|//)","i")).test(url)){return url}else if((new RegExp("^[^\/]*\\.php(\\?.*)?$","i")).test(url)){if(url.indexOf('/')===0){url=url.substring(1)}
return elgg.config.wwwroot+url}else if((new RegExp("^[^/\\?\\#]*\\.","i")).test(url)){return'http://'+url}else{if(url.indexOf('/')===0){url=url.substring(1)}
return elgg.config.wwwroot+url}};elgg.deprecated_notice=function(msg,dep_version){if(elgg.is_admin_logged_in()){msg="Deprecated in Elgg "+dep_version+": "+msg;if(typeof console!=="undefined"){console.info(msg)}}};elgg.forward=function(url){var dest=elgg.normalize_url(url);if(dest==location.href){location.reload()}
$(window).on('hashchange',function(){location.reload()});location.href=dest};elgg.parse_url=function(url,component,expand){expand=expand||!1;component=component||!1;var re_str='^(?:(?![^:@]+:[^:@/]*@)([^:/?#.]+):)?(?://)?';re_str+='((?:(([^:@]*)(?::([^:@]*))?)?@)?';re_str+='([^:/?#]*)(?::(\\d*))?)';re_str+='(((/(?:[^?#](?![^?#/]*\\.[^?#/.]+(?:[?#]|$)))*/?)?([^?#/]*))';re_str+='(?:\\?([^#]*))?';re_str+='(?:#(.*))?)';var keys={1:"scheme",4:"user",5:"pass",6:"host",7:"port",9:"path",12:"query",13:"fragment"};var results={};if(url.indexOf('mailto:')===0){results.scheme='mailto';results.path=url.replace('mailto:','');return results}
if(url.indexOf('javascript:')===0){results.scheme='javascript';results.path=url.replace('javascript:','');return results}
var re=new RegExp(re_str);var matches=re.exec(url);for(var i in keys){if(matches[i]){results[keys[i]]=matches[i]}}
if(expand&&typeof(results.query)!='undefined'){results.query=elgg.parse_str(results.query)}
if(component){if(typeof(results[component])!='undefined'){return results[component]}else{return!1}}
return results};elgg.parse_str=function(string){var params={},result,key,value,re=/([^&=]+)=?([^&]*)/g,re2=/\[\]$/;while(result=re.exec(string)){key=decodeURIComponent(result[1].replace(/\+/g,' '));value=decodeURIComponent(result[2].replace(/\+/g,' '));if(re2.test(key)){key=key.replace(re2,'');if(!params[key]){params[key]=[]}
params[key].push(value)}else{params[key]=value}}
return params};elgg.getSelectorFromUrlFragment=function(url){var fragment=url.split('#')[1];if(fragment){if(fragment.indexOf('.')>-1){return fragment}else{return'#'+fragment}}
return''};elgg.get_logged_in_user_guid=function(){return elgg.user?elgg.user.guid:0};elgg.is_logged_in=function(){return elgg.get_logged_in_user_guid()>0};elgg.is_admin_logged_in=function(){return elgg.user?elgg.user.admin:!1};elgg.get_site_url=function(){return elgg.config.wwwroot};elgg.get_simplecache_url=function(view,subview){elgg.assertTypeOf('string',view);var lastcache,path;if(elgg.config.simplecache_enabled){lastcache=elgg.config.lastcache}else{lastcache=0}
if(!subview){path='/cache/'+lastcache+'/'+elgg.config.viewtype+'/'+view}else{elgg.assertTypeOf('string',subview);if((view==='js'||view==='css')&&0===subview.indexOf(view+'/')){subview=subview.substring(view.length+1)}
path='/cache/'+lastcache+'/'+elgg.config.viewtype+'/'+view+'/'+subview}
return elgg.normalize_url(path)};$(document).on('click','*[data-confirm]',function(e){var confirmText=$(this).data('confirm');if(!confirm(confirmText)){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();return!1}});document.addEventListener('scroll',function(){if($(document).scrollTop()>1000){$('#elgg-scroll-to-top').show()}else{$('#elgg-scroll-to-top').hide()}},{passive:!0});export default elgg