/*!
* focus-trap 7.6.4
* @license MIT, https://github.com/focus-trap/focus-trap/blob/master/LICENSE
*/
import{tabbable,focusable,isTabbable,getTabIndex,isFocusable}from 'tabbable';function _arrayLikeToArray(r,a){(null==a||a>r.length)&&(a=r.length);for(var e=0,n=Array(a);e<a;e++)n[e]=r[e];return n}
function _arrayWithoutHoles(r){if(Array.isArray(r))return _arrayLikeToArray(r);}
function _defineProperty(e,r,t){return(r=_toPropertyKey(r))in e?Object.defineProperty(e,r,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[r]=t,e}
function _iterableToArray(r){if("undefined"!=typeof Symbol&&null!=r[Symbol.iterator]||null!=r["@@iterator"])return Array.from(r);}
function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}
function ownKeys(e,r){var t=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);r&&(o=o.filter(function(r){return Object.getOwnPropertyDescriptor(e,r).enumerable})),t.push.apply(t,o)}
return t}
function _objectSpread2(e){for(var r=1;r<arguments.length;r++){var t=null!=arguments[r]?arguments[r]:{};r%2?ownKeys(Object(t),!0).forEach(function(r){_defineProperty(e,r,t[r])}):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(t)):ownKeys(Object(t)).forEach(function(r){Object.defineProperty(e,r,Object.getOwnPropertyDescriptor(t,r))})}
return e}
function _toConsumableArray(r){return _arrayWithoutHoles(r)||_iterableToArray(r)||_unsupportedIterableToArray(r)||_nonIterableSpread()}
function _toPrimitive(t,r){if("object"!=typeof t||!t)return t;var e=t[Symbol.toPrimitive];if(undefined!==e){var i=e.call(t,r||"default");if("object"!=typeof i)return i;throw new TypeError("@@toPrimitive must return a primitive value.")}
return("string"===r?String:Number)(t)}
function _toPropertyKey(t){var i=_toPrimitive(t,"string");return"symbol"==typeof i?i:i+""}
function _unsupportedIterableToArray(r,a){if(r){if("string"==typeof r)return _arrayLikeToArray(r,a);var t={}.toString.call(r).slice(8,-1);return"Object"===t&&r.constructor&&(t=r.constructor.name),"Map"===t||"Set"===t?Array.from(r):"Arguments"===t||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(t)?_arrayLikeToArray(r,a):undefined}}
var activeFocusTraps={activateTrap:function activateTrap(trapStack,trap){if(trapStack.length>0){var activeTrap=trapStack[trapStack.length-1];if(activeTrap!==trap){activeTrap._setPausedState(!0)}}
var trapIndex=trapStack.indexOf(trap);if(trapIndex===-1){trapStack.push(trap)}else{trapStack.splice(trapIndex,1);trapStack.push(trap)}},deactivateTrap:function deactivateTrap(trapStack,trap){var trapIndex=trapStack.indexOf(trap);if(trapIndex!==-1){trapStack.splice(trapIndex,1)}
if(trapStack.length>0&&!trapStack[trapStack.length-1]._isManuallyPaused()){trapStack[trapStack.length-1]._setPausedState(!1)}}};var isSelectableInput=function isSelectableInput(node){return node.tagName&&node.tagName.toLowerCase()==='input'&&typeof node.select==='function'};var isEscapeEvent=function isEscapeEvent(e){return(e===null||e===undefined?undefined:e.key)==='Escape'||(e===null||e===undefined?undefined:e.key)==='Esc'||(e===null||e===undefined?undefined:e.keyCode)===27};var isTabEvent=function isTabEvent(e){return(e===null||e===undefined?undefined:e.key)==='Tab'||(e===null||e===undefined?undefined:e.keyCode)===9};var isKeyForward=function isKeyForward(e){return isTabEvent(e)&&!e.shiftKey};var isKeyBackward=function isKeyBackward(e){return isTabEvent(e)&&e.shiftKey};var delay=function delay(fn){return setTimeout(fn,0)};var valueOrHandler=function valueOrHandler(value){for(var _len=arguments.length,params=new Array(_len>1?_len-1:0),_key=1;_key<_len;_key++){params[_key-1]=arguments[_key]}
return typeof value==='function'?value.apply(undefined,params):value};var getActualTarget=function getActualTarget(event){return event.target.shadowRoot&&typeof event.composedPath==='function'?event.composedPath()[0]:event.target};var internalTrapStack=[];var createFocusTrap=function createFocusTrap(elements,userOptions){var doc=(userOptions===null||userOptions===undefined?undefined:userOptions.document)||document;var trapStack=(userOptions===null||userOptions===undefined?undefined:userOptions.trapStack)||internalTrapStack;var config=_objectSpread2({returnFocusOnDeactivate:!0,escapeDeactivates:!0,delayInitialFocus:!0,isKeyForward:isKeyForward,isKeyBackward:isKeyBackward},userOptions);var state={containers:[],containerGroups:[],tabbableGroups:[],nodeFocusedBeforeActivation:null,mostRecentlyFocusedNode:null,active:!1,paused:!1,manuallyPaused:!1,delayInitialFocusTimer:undefined,recentNavEvent:undefined};var trap;var getOption=function getOption(configOverrideOptions,optionName,configOptionName){return configOverrideOptions&&configOverrideOptions[optionName]!==undefined?configOverrideOptions[optionName]:config[configOptionName||optionName]};var findContainerIndex=function findContainerIndex(element,event){var composedPath=typeof(event===null||event===undefined?undefined:event.composedPath)==='function'?event.composedPath():undefined;return state.containerGroups.findIndex(function(_ref){var container=_ref.container,tabbableNodes=_ref.tabbableNodes;return container.contains(element)||(composedPath===null||composedPath===undefined?undefined:composedPath.includes(container))||tabbableNodes.find(function(node){return node===element})})};var getNodeForOption=function getNodeForOption(optionName){var _ref2=arguments.length>1&&arguments[1]!==undefined?arguments[1]:{},_ref2$hasFallback=_ref2.hasFallback,hasFallback=_ref2$hasFallback===undefined?!1:_ref2$hasFallback,_ref2$params=_ref2.params,params=_ref2$params===undefined?[]:_ref2$params;var optionValue=config[optionName];if(typeof optionValue==='function'){optionValue=optionValue.apply(undefined,_toConsumableArray(params))}
if(optionValue===!0){optionValue=undefined}
if(!optionValue){if(optionValue===undefined||optionValue===!1){return optionValue}
throw new Error("`".concat(optionName,"` was specified but was not a node, or did not return a node"))}
var node=optionValue;if(typeof optionValue==='string'){try{node=doc.querySelector(optionValue)}catch(err){throw new Error("`".concat(optionName,"` appears to be an invalid selector; error=\"").concat(err.message,"\""))}
if(!node){if(!hasFallback){throw new Error("`".concat(optionName,"` as selector refers to no known node"))}}}
return node};var getInitialFocusNode=function getInitialFocusNode(){var node=getNodeForOption('initialFocus',{hasFallback:!0});if(node===!1){return!1}
if(node===undefined||node&&!isFocusable(node,config.tabbableOptions)){if(findContainerIndex(doc.activeElement)>=0){node=doc.activeElement}else{var firstTabbableGroup=state.tabbableGroups[0];var firstTabbableNode=firstTabbableGroup&&firstTabbableGroup.firstTabbableNode;node=firstTabbableNode||getNodeForOption('fallbackFocus')}}else if(node===null){node=getNodeForOption('fallbackFocus')}
if(!node){throw new Error('Your focus-trap needs to have at least one focusable element')}
return node};var updateTabbableNodes=function updateTabbableNodes(){state.containerGroups=state.containers.map(function(container){var tabbableNodes=tabbable(container,config.tabbableOptions);var focusableNodes=focusable(container,config.tabbableOptions);var firstTabbableNode=tabbableNodes.length>0?tabbableNodes[0]:undefined;var lastTabbableNode=tabbableNodes.length>0?tabbableNodes[tabbableNodes.length-1]:undefined;var firstDomTabbableNode=focusableNodes.find(function(node){return isTabbable(node)});var lastDomTabbableNode=focusableNodes.slice().reverse().find(function(node){return isTabbable(node)});var posTabIndexesFound=!!tabbableNodes.find(function(node){return getTabIndex(node)>0});return{container:container,tabbableNodes:tabbableNodes,focusableNodes:focusableNodes,posTabIndexesFound:posTabIndexesFound,firstTabbableNode:firstTabbableNode,lastTabbableNode:lastTabbableNode,firstDomTabbableNode:firstDomTabbableNode,lastDomTabbableNode:lastDomTabbableNode,nextTabbableNode:function nextTabbableNode(node){var forward=arguments.length>1&&arguments[1]!==undefined?arguments[1]:!0;var nodeIdx=tabbableNodes.indexOf(node);if(nodeIdx<0){if(forward){return focusableNodes.slice(focusableNodes.indexOf(node)+1).find(function(el){return isTabbable(el)})}
return focusableNodes.slice(0,focusableNodes.indexOf(node)).reverse().find(function(el){return isTabbable(el)})}
return tabbableNodes[nodeIdx+(forward?1:-1)]}}});state.tabbableGroups=state.containerGroups.filter(function(group){return group.tabbableNodes.length>0});if(state.tabbableGroups.length<=0&&!getNodeForOption('fallbackFocus')){throw new Error('Your focus-trap must have at least one container with at least one tabbable node in it at all times')}
if(state.containerGroups.find(function(g){return g.posTabIndexesFound})&&state.containerGroups.length>1){throw new Error("At least one node with a positive tabindex was found in one of your focus-trap's multiple containers. Positive tabindexes are only supported in single-container focus-traps.")}};var _getActiveElement=function getActiveElement(el){var activeElement=el.activeElement;if(!activeElement){return}
if(activeElement.shadowRoot&&activeElement.shadowRoot.activeElement!==null){return _getActiveElement(activeElement.shadowRoot)}
return activeElement};var _tryFocus=function tryFocus(node){if(node===!1){return}
if(node===_getActiveElement(document)){return}
if(!node||!node.focus){_tryFocus(getInitialFocusNode());return}
node.focus({preventScroll:!!config.preventScroll});state.mostRecentlyFocusedNode=node;if(isSelectableInput(node)){node.select()}};var getReturnFocusNode=function getReturnFocusNode(previousActiveElement){var node=getNodeForOption('setReturnFocus',{params:[previousActiveElement]});return node?node:node===!1?!1:previousActiveElement};var findNextNavNode=function findNextNavNode(_ref3){var target=_ref3.target,event=_ref3.event,_ref3$isBackward=_ref3.isBackward,isBackward=_ref3$isBackward===undefined?!1:_ref3$isBackward;target=target||getActualTarget(event);updateTabbableNodes();var destinationNode=null;if(state.tabbableGroups.length>0){var containerIndex=findContainerIndex(target,event);var containerGroup=containerIndex>=0?state.containerGroups[containerIndex]:undefined;if(containerIndex<0){if(isBackward){destinationNode=state.tabbableGroups[state.tabbableGroups.length-1].lastTabbableNode}else{destinationNode=state.tabbableGroups[0].firstTabbableNode}}else if(isBackward){var startOfGroupIndex=state.tabbableGroups.findIndex(function(_ref4){var firstTabbableNode=_ref4.firstTabbableNode;return target===firstTabbableNode});if(startOfGroupIndex<0&&(containerGroup.container===target||isFocusable(target,config.tabbableOptions)&&!isTabbable(target,config.tabbableOptions)&&!containerGroup.nextTabbableNode(target,!1))){startOfGroupIndex=containerIndex}
if(startOfGroupIndex>=0){var destinationGroupIndex=startOfGroupIndex===0?state.tabbableGroups.length-1:startOfGroupIndex-1;var destinationGroup=state.tabbableGroups[destinationGroupIndex];destinationNode=getTabIndex(target)>=0?destinationGroup.lastTabbableNode:destinationGroup.lastDomTabbableNode}else if(!isTabEvent(event)){destinationNode=containerGroup.nextTabbableNode(target,!1)}}else{var lastOfGroupIndex=state.tabbableGroups.findIndex(function(_ref5){var lastTabbableNode=_ref5.lastTabbableNode;return target===lastTabbableNode});if(lastOfGroupIndex<0&&(containerGroup.container===target||isFocusable(target,config.tabbableOptions)&&!isTabbable(target,config.tabbableOptions)&&!containerGroup.nextTabbableNode(target))){lastOfGroupIndex=containerIndex}
if(lastOfGroupIndex>=0){var _destinationGroupIndex=lastOfGroupIndex===state.tabbableGroups.length-1?0:lastOfGroupIndex+1;var _destinationGroup=state.tabbableGroups[_destinationGroupIndex];destinationNode=getTabIndex(target)>=0?_destinationGroup.firstTabbableNode:_destinationGroup.firstDomTabbableNode}else if(!isTabEvent(event)){destinationNode=containerGroup.nextTabbableNode(target)}}}else{destinationNode=getNodeForOption('fallbackFocus')}
return destinationNode};var checkPointerDown=function checkPointerDown(e){var target=getActualTarget(e);if(findContainerIndex(target,e)>=0){return}
if(valueOrHandler(config.clickOutsideDeactivates,e)){trap.deactivate({returnFocus:config.returnFocusOnDeactivate});return}
if(valueOrHandler(config.allowOutsideClick,e)){return}
e.preventDefault()};var checkFocusIn=function checkFocusIn(event){var target=getActualTarget(event);var targetContained=findContainerIndex(target,event)>=0;if(targetContained||target instanceof Document){if(targetContained){state.mostRecentlyFocusedNode=target}}else{event.stopImmediatePropagation();var nextNode;var navAcrossContainers=!0;if(state.mostRecentlyFocusedNode){if(getTabIndex(state.mostRecentlyFocusedNode)>0){var mruContainerIdx=findContainerIndex(state.mostRecentlyFocusedNode);var tabbableNodes=state.containerGroups[mruContainerIdx].tabbableNodes;if(tabbableNodes.length>0){var mruTabIdx=tabbableNodes.findIndex(function(node){return node===state.mostRecentlyFocusedNode});if(mruTabIdx>=0){if(config.isKeyForward(state.recentNavEvent)){if(mruTabIdx+1<tabbableNodes.length){nextNode=tabbableNodes[mruTabIdx+1];navAcrossContainers=!1}}else{if(mruTabIdx-1>=0){nextNode=tabbableNodes[mruTabIdx-1];navAcrossContainers=!1}}}}}else{if(!state.containerGroups.some(function(g){return g.tabbableNodes.some(function(n){return getTabIndex(n)>0})})){navAcrossContainers=!1}}}else{navAcrossContainers=!1}
if(navAcrossContainers){nextNode=findNextNavNode({target:state.mostRecentlyFocusedNode,isBackward:config.isKeyBackward(state.recentNavEvent)})}
if(nextNode){_tryFocus(nextNode)}else{_tryFocus(state.mostRecentlyFocusedNode||getInitialFocusNode())}}
state.recentNavEvent=undefined};var checkKeyNav=function checkKeyNav(event){var isBackward=arguments.length>1&&arguments[1]!==undefined?arguments[1]:!1;state.recentNavEvent=event;var destinationNode=findNextNavNode({event:event,isBackward:isBackward});if(destinationNode){if(isTabEvent(event)){event.preventDefault()}
_tryFocus(destinationNode)}};var checkTabKey=function checkTabKey(event){if(config.isKeyForward(event)||config.isKeyBackward(event)){checkKeyNav(event,config.isKeyBackward(event))}};var checkEscapeKey=function checkEscapeKey(event){if(isEscapeEvent(event)&&valueOrHandler(config.escapeDeactivates,event)!==!1){event.preventDefault();trap.deactivate()}};var checkClick=function checkClick(e){var target=getActualTarget(e);if(findContainerIndex(target,e)>=0){return}
if(valueOrHandler(config.clickOutsideDeactivates,e)){return}
if(valueOrHandler(config.allowOutsideClick,e)){return}
e.preventDefault();e.stopImmediatePropagation()};var addListeners=function addListeners(){if(!state.active){return}
activeFocusTraps.activateTrap(trapStack,trap);state.delayInitialFocusTimer=config.delayInitialFocus?delay(function(){_tryFocus(getInitialFocusNode())}):_tryFocus(getInitialFocusNode());doc.addEventListener('focusin',checkFocusIn,!0);doc.addEventListener('mousedown',checkPointerDown,{capture:!0,passive:!1});doc.addEventListener('touchstart',checkPointerDown,{capture:!0,passive:!1});doc.addEventListener('click',checkClick,{capture:!0,passive:!1});doc.addEventListener('keydown',checkTabKey,{capture:!0,passive:!1});doc.addEventListener('keydown',checkEscapeKey);return trap};var removeListeners=function removeListeners(){if(!state.active){return}
doc.removeEventListener('focusin',checkFocusIn,!0);doc.removeEventListener('mousedown',checkPointerDown,!0);doc.removeEventListener('touchstart',checkPointerDown,!0);doc.removeEventListener('click',checkClick,!0);doc.removeEventListener('keydown',checkTabKey,!0);doc.removeEventListener('keydown',checkEscapeKey);return trap};var checkDomRemoval=function checkDomRemoval(mutations){var isFocusedNodeRemoved=mutations.some(function(mutation){var removedNodes=Array.from(mutation.removedNodes);return removedNodes.some(function(node){return node===state.mostRecentlyFocusedNode})});if(isFocusedNodeRemoved){_tryFocus(getInitialFocusNode())}};var mutationObserver=typeof window!=='undefined'&&'MutationObserver' in window?new MutationObserver(checkDomRemoval):undefined;var updateObservedNodes=function updateObservedNodes(){if(!mutationObserver){return}
mutationObserver.disconnect();if(state.active&&!state.paused){state.containers.map(function(container){mutationObserver.observe(container,{subtree:!0,childList:!0})})}};trap={get active(){return state.active},get paused(){return state.paused},activate:function activate(activateOptions){if(state.active){return this}
var onActivate=getOption(activateOptions,'onActivate');var onPostActivate=getOption(activateOptions,'onPostActivate');var checkCanFocusTrap=getOption(activateOptions,'checkCanFocusTrap');if(!checkCanFocusTrap){updateTabbableNodes()}
state.active=!0;state.paused=!1;state.nodeFocusedBeforeActivation=doc.activeElement;onActivate===null||onActivate===undefined||onActivate();var finishActivation=function finishActivation(){if(checkCanFocusTrap){updateTabbableNodes()}
addListeners();updateObservedNodes();onPostActivate===null||onPostActivate===undefined||onPostActivate()};if(checkCanFocusTrap){checkCanFocusTrap(state.containers.concat()).then(finishActivation,finishActivation);return this}
finishActivation();return this},deactivate:function deactivate(deactivateOptions){if(!state.active){return this}
var options=_objectSpread2({onDeactivate:config.onDeactivate,onPostDeactivate:config.onPostDeactivate,checkCanReturnFocus:config.checkCanReturnFocus},deactivateOptions);clearTimeout(state.delayInitialFocusTimer);state.delayInitialFocusTimer=undefined;removeListeners();state.active=!1;state.paused=!1;updateObservedNodes();activeFocusTraps.deactivateTrap(trapStack,trap);var onDeactivate=getOption(options,'onDeactivate');var onPostDeactivate=getOption(options,'onPostDeactivate');var checkCanReturnFocus=getOption(options,'checkCanReturnFocus');var returnFocus=getOption(options,'returnFocus','returnFocusOnDeactivate');onDeactivate===null||onDeactivate===undefined||onDeactivate();var finishDeactivation=function finishDeactivation(){delay(function(){if(returnFocus){_tryFocus(getReturnFocusNode(state.nodeFocusedBeforeActivation))}
onPostDeactivate===null||onPostDeactivate===undefined||onPostDeactivate()})};if(returnFocus&&checkCanReturnFocus){checkCanReturnFocus(getReturnFocusNode(state.nodeFocusedBeforeActivation)).then(finishDeactivation,finishDeactivation);return this}
finishDeactivation();return this},pause:function pause(pauseOptions){if(!state.active){return this}
state.manuallyPaused=!0;return this._setPausedState(!0,pauseOptions)},unpause:function unpause(unpauseOptions){if(!state.active){return this}
state.manuallyPaused=!1;if(trapStack[trapStack.length-1]!==this){return this}
return this._setPausedState(!1,unpauseOptions)},updateContainerElements:function updateContainerElements(containerElements){var elementsAsArray=[].concat(containerElements).filter(Boolean);state.containers=elementsAsArray.map(function(element){return typeof element==='string'?doc.querySelector(element):element});if(state.active){updateTabbableNodes()}
updateObservedNodes();return this}};Object.defineProperties(trap,{_isManuallyPaused:{value:function value(){return state.manuallyPaused}},_setPausedState:{value:function value(paused,options){if(state.paused===paused){return this}
state.paused=paused;if(paused){var onPause=getOption(options,'onPause');var onPostPause=getOption(options,'onPostPause');onPause===null||onPause===undefined||onPause();removeListeners();updateObservedNodes();onPostPause===null||onPostPause===undefined||onPostPause()}else{var onUnpause=getOption(options,'onUnpause');var onPostUnpause=getOption(options,'onPostUnpause');onUnpause===null||onUnpause===undefined||onUnpause();updateTabbableNodes();addListeners();updateObservedNodes();onPostUnpause===null||onPostUnpause===undefined||onPostUnpause()}
return this}}});trap.updateContainerElements(elements);return trap};export{createFocusTrap}