import 'jquery';import '../jquery.colorbox.js';import elgg from 'elgg';import Ajax from 'elgg/Ajax';import hooks from 'elgg/hooks';import popup from 'elgg/popup';import*as focusTrap from 'focus-trap';let menuTrap;var lightbox={getOptions:function(opts){if(!$.isPlainObject(opts)){opts={}}
var defaults=elgg.data.lightbox;if(!defaults.reposition){defaults.reposition=$(window).height()>600}
var settings=$.extend({},defaults,opts);settings=hooks.trigger('getOptions','ui.lightbox',null,settings);settings.trapFocus=!1;const customOnComplete=settings.onComplete;settings.onComplete=function(){if(typeof customOnComplete==='function'){customOnComplete()}
if($('#cboxContent .elgg-input-longtext').length>0){return}
menuTrap=focusTrap.createFocusTrap('#cboxContent',{returnFocusOnDeactivate:!1,clickOutsideDeactivates:!1,allowOutsideClick:!0,escapeDeactivates:!1});menuTrap.activate()};const customOnClosed=settings.onClosed;settings.onClosed=function(){if(typeof customOnClosed==='function'){customOnClosed()}
if(typeof menuTrap!=='undefined'){menuTrap.deactivate()}};return settings},bind:function(selector,opts,use_element_data){if(!$.isPlainObject(opts)){opts={}}
if(use_element_data===!1){$(selector).colorbox(lightbox.getOptions(opts));return}
$(document).off('click.lightbox',selector).on('click.lightbox',selector,function(e){popup.close();$('.elgg-system-messages .elgg-message').remove();e.preventDefault();var $this=$(this),href=$this.prop('href')||$this.prop('src'),dataOpts=$this.data('colorboxOpts'),currentOpts={};if(!$.isPlainObject(dataOpts)){dataOpts={}}
if(!dataOpts.href&&href){dataOpts.href=href}
$.extend(currentOpts,opts,dataOpts);if(currentOpts.inline&&currentOpts.href){currentOpts.href=elgg.getSelectorFromUrlFragment(currentOpts.href)}
if(currentOpts.photo||currentOpts.inline||currentOpts.iframe||currentOpts.html){lightbox.open(currentOpts);return}
currentOpts.ajaxLoadWithDependencies=!0;lightbox.open(currentOpts)});$(window).off('resize.lightbox').on('resize.lightbox',function(){elgg.data.lightbox.reposition=$(window).height()>600;lightbox.resize()})},open:function(opts){var currentOpts=lightbox.getOptions(opts);if(!currentOpts.ajaxLoadWithDependencies){$.colorbox(currentOpts);return}
var href=currentOpts.href;currentOpts.href=!1;var data=currentOpts.data;currentOpts.data=undefined;$.colorbox(currentOpts);var ajax=new Ajax(!1);ajax.path(href,{data:data}).done(function(output){currentOpts.html=output;$.colorbox(currentOpts);currentOpts.html=undefined}).fail(function(){$.colorbox.close()})},close:$.colorbox.close,resize:$.colorbox.resize};lightbox.bind(".elgg-lightbox");lightbox.bind(".elgg-lightbox-photo",{photo:!0});lightbox.bind(".elgg-lightbox-inline",{inline:!0});lightbox.bind(".elgg-lightbox-iframe",{iframe:!0});export default lightbox